name       : mkfontscale
version    : 1.1.3
release    : 5
source     :
    - https://www.x.org/releases/individual/app/mkfontscale-1.1.3.tar.gz : 449b8ccd44133e260eafab55f18937c09fd4846b87f288f1c9611e4810e13bb2
license    :
    - MIT
component  : xorg.apps
summary    : |
    X.Org Applications: mkfontscale
description: |
    X.Org Applications: mkfontscale
builddeps  :
    - pkgconfig(fontenc)
    - pkgconfig(freetype2)
    - pkgconfig(xproto)
    - pkgconfig(xorg-macros)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
