name       : mkfontscale
version    : 1.2.0
release    : 7
source     :
    - https://www.x.org/releases/individual/app/mkfontscale-1.2.0.tar.gz : 447e64b1569d32a676a0405d4f804531551a0a1a3becde97fbdcb50224014679
license    : MIT
component  : xorg.apps
summary    : |
    X.Org Applications: mkfontscale
description: |
    Create an index of scalable font files for X
builddeps  :
    - pkgconfig(fontenc)
    - pkgconfig(freetype2)
    - pkgconfig(xproto)
    - pkgconfig(xorg-macros)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
