name       : mkfontscale
version    : 1.1.2
release    : 3
source     :
    - https://www.x.org/releases/individual/app/mkfontscale-1.1.2.tar.gz : 8bba59e60fbc4cb082092cf6b67e810b47b4fe64fbc77dbea1d7e7d55312b2e4
license    :
    - MIT
component  : xorg.apps
summary    : |
    X.Org Applications: mkfontscale
description: |
    X.Org Applications: mkfontscale
builddeps  :
    - pkgconfig(fontenc)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
