name       : mkfontscale
version    : 1.2.1
release    : 13
source     :
    - https://www.x.org/releases/individual/app/mkfontscale-1.2.1.tar.gz : e5b687029e44d0bd3ccd254a4da6a5cbfc40350aa8b43fcca16ef6e9b9bb9f22
license    : MIT
component  : xorg.apps
summary    : |
    X.Org Applications: mkfontscale
description: |
    Create an index of scalable font files for X
replaces   :
    - mkfontdir
builddeps  :
    - pkgconfig(fontenc)
    - pkgconfig(freetype2)
    - pkgconfig(xproto)
    - pkgconfig(xorg-macros)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
